server:
  port: 8081
spring:
  application:
    name: config-server
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/shopdev
    username: root
    password: nakanomiku
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        comment_sql: true
  mail:
    host: xxxx
    port: 587
    username: xxx
    password: xxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
        ssl:
          enable: true
  kafka:
    bootstrap-servers: localhost:9092
    auto-offset-reset: earliest
    enable-auto-commit: false
  redis:
    host: localhost
    port: 6379
    namespace: spring:session
  session:
    store-type: redis
    redis:
      namespace: spring:session
logging:
  config: classpath:log4j2.yaml
